# Generated by Django 5.2.5 on 2025-08-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('cover', models.CharField(max_length=255)),
                ('rating', models.CharField(max_length=255)),
                ('review', models.CharField(max_length=255)),
                ('swapspot', models.CharField(max_length=255)),
            ],
        ),
    ]
