# Generated by Django 5.2.5 on 2025-08-07 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.IntegerField(max_length=255),
        ),
    ]
