# Generated by Django 5.2.5 on 2025-08-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='reservedBy',
            field=models.CharField(default='Unreserved', max_length=255),
        ),
    ]
